export const SET_SINGER = "SET_SINGER"

export const SET_PLAYLIST = "SET_PLAYLIST"

export const SET_PLAYING = "SET_PLAYING"

export const SET_CURRENTINDEX = "SET_CURRENTINDEX"

export const SET_SEQUENCELIST = "SET_SEQUENCELIST"

export const SET_PLAYMODE = "SET_PLAYMODE"

export const ADD_FAVORITE = "ADD_FAVORITE"

export const DELETE_FAVORITE = "DELETE_FAVORITE"

export const REFRESH_MYALBUM = "REFRESH_MYALBUM"

export const REFRESH_FAVORITE = "REFRESH_FAVORITE"

export const REFRESH_COLLECTALBUM = "REFRESH_COLLECTALBUM"

export const DELETE_PLAYLIST = "DELETE_PLAYLIST"


